import Link from "next/link";
import { notFound } from "next/navigation";
import { getManifest, getReport, reportsForStore } from "@/lib/data";
import { ReportHeader } from "@/components/ReportHeader";
import { CategoryNav } from "@/components/CategoryNav";
import { ShareButton } from "@/components/ShareButton";

export const dynamic = "force-dynamic";

export default async function ReportLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ slug: string; id: string }>;
}) {
  const { slug, id } = await params;
  const [report, manifest] = await Promise.all([getReport(slug, id), getManifest()]);
  if (!report) notFound();

  const history = reportsForStore(manifest, slug, id).slice(0, 6);

  return (
    <div className="min-h-screen bg-[#f9f8f6]">
      <header className="bg-white h-[73px] border-b border-[#E5E5E5] flex items-center px-6 lg:px-8">
        <div className="max-w-[1600px] w-full mx-auto flex items-center justify-between gap-3">
          <Link href="/" className="text-sm text-[#6B6B6B] hover:text-[#1A1A1A]">
            ← All reports
          </Link>
          <div className="flex items-center gap-2">
            <Link
              href={`/progress/${slug}`}
              className="text-sm font-medium text-[#1A1A1A] bg-[#f0efed] hover:bg-[#EDECE8] px-3.5 py-2 rounded-lg transition-colors"
            >
              Progress
            </Link>
            <ShareButton slug={slug} id={id} />
            <Link
              href="/instructions"
              className="text-sm font-medium text-[#1A1A1A] bg-[#f0efed] hover:bg-[#EDECE8] px-3.5 py-2 rounded-lg transition-colors"
            >
              CLI Instructions
            </Link>
          </div>
        </div>
      </header>

      <main className="max-w-[1600px] mx-auto px-5 lg:px-8 pb-16">
        <ReportHeader report={report} slug={slug} history={history} />
        <CategoryNav slug={slug} id={id} />

        {children}

        <footer className="mt-12 pt-5 border-t border-[#E5E5E5] text-[11.5px] text-[#9A9A9A] leading-relaxed">
          <b className="text-[#6B6B6B]">Methodology.</b> Performance and vitals figures are a single live Lighthouse
          (mobile) run against the storefront, not the throttled public PageSpeed API — lab data, not real-user field
          data. Site health, pixel/consent, theme code, and theme structure checks are static/live analysis of the
          same live storefront and its theme source. The roadmap is synthesized by severity across every section in
          this report, regardless of which page it's shown on.
          {report.aiUsage && (
            <>
              {" "}
              <b className="text-[#6B6B6B]">AI usage.</b> The executive summary, UX opportunities, and AI
              performance/accessibility suggestions above were generated by {report.aiUsage.model} using{" "}
              {report.aiUsage.inputTokens.toLocaleString()} input and {report.aiUsage.outputTokens.toLocaleString()}{" "}
              output tokens ({report.aiUsage.totalTokens.toLocaleString()} total, ≈$
              {report.aiUsage.estimatedCostUsd.toFixed(4)}).
            </>
          )}
        </footer>
      </main>
    </div>
  );
}
