export interface ReleaseNote {
  version: string;
  date: string; // YYYY-MM-DD
  title: string;
  notes: string[];
}

// Newest first. Version bumps the minor number for a normal shipped change; a major bump (2.0)
// is reserved for a genuinely foundational shift, not a rule enforced by code. See the
// feedback-release-notes memory for the standing instruction to add an entry here (and bump the
// version) as part of shipping any user-visible change — this file is the source of truth for
// both the in-app "release notes" page and that version number.
export const RELEASE_NOTES: ReleaseNote[] = [
  {
    version: "1.33",
    date: "2026-08-25",
    title: "A Recommendations tab for the client, and a Theme Check that names the theme",
    notes: [
      "**There is a new Recommendations tab, and it is the tab you present.** Every other tab in a report is evidence; this one is the argument. It reads the whole finished report — Lighthouse, axe, health, consent, security, SEO/GEO, agent readiness, the UX audit, the theme codebase and, when the store has GA4 linked, its real traffic and revenue — and comes back with the five to ten things to do next, ordered by how much each should move **conversion** rather than by how severe it is technically. A critical lint error no shopper can perceive ranks below a slow product page, and related technical findings are merged into one business-level action instead of listed separately.",
      "**Each recommendation is written to be said out loud in a client meeting.** An action phrased as something to do, the part of the experience it moves, why it matters commercially, what we would actually do, what to expect from it, and the specific figures from the audit that justify it. The tone is deliberately a partnership rather than a verdict — we often built the site ourselves, so a finding is what the storefront has outgrown or what the platform now makes possible, never a mistake someone made. It opens on **what is already working**, cited with real numbers, before anything it suggests changing. Expected impact stays honest and directional: it will never invent a percentage lift for your store.",
      "**Copy for deck** puts the whole set on the clipboard as structured markdown, headline and strengths included, ready to paste into slides. The tab also leads a shared report, ahead of the technical sections it was derived from.",
      "**Theme Check now tells you what theme the store actually runs.** A new **Theme & Codebase** section reads the theme's own `config/settings_schema.json` and reports its name, version and author — and, more usefully, whether that is a stock Shopify theme, a **fork** of one (the name still says Dawn but the author doesn't, so upstream releases can no longer be merged in), a third-party/agency theme, or something custom-built. It reads themes whose settings file has a trailing comma, which Shopify tolerates and a strict JSON parser does not.",
      "**And what the codebase is made of.** Template architecture and section groups, theme blocks and app-block support, Liquid line count, asset count and weight with the largest files named, JS/CSS totals, the build tooling actually committed, the front-end libraries genuinely detectable in the code, localization, metafield and metaobject usage, and whether lint config and CI are in the repo at all.",
      "**Plus the codebase opportunities that fall out of it, each citing its own evidence.** Deprecated `{% include %}` tags with the files they are in; oversized images and animated GIFs with their real sizes; legacy `.ttf`/`.otf` fonts; several generations of the same content-hashed bundle left behind in `assets/`; page templates owned by a page-builder app rather than the theme; templates still Liquid-only in an otherwise Online Store 2.0 theme; missing header/footer section groups; theme blocks or app blocks never adopted; jQuery, named down to the file it is bundled inside. All of it is a file scan, so it needs no API key — and it is careful about the reverse mistake too: a `_backup_do_not_delete` template is never recommended for migration, and files that merely share a filename prefix are not reported as abandoned build output.",
      "**A theme whose build output is committed without its build is now called out as its own finding.** Hashed bundles in `assets/` with no `package.json` or bundler config in the repo does not mean \"no build step\" — it means the build lives on somebody's laptop and nobody else can reproduce it, which is different advice.",
      "The AI theme-architecture assessment is now handed all of this as grounding, so its narrative names the theme and version instead of inferring them, and it adds only the opportunities a file scan could not find. Everything new here also flows into the roadmap and the Dev To-Do like any other section. New flags: `--skip-recommendations`, and both checks are toggleable from the dashboard run form.",
    ],
  },
  {
    version: "1.32",
    date: "2026-08-21",
    title: "CRO Audits — a second report type, for the conversion deck",
    notes: [
      "**There is a new CRO Audits tab, and it is a separate deliverable from a site audit.** A site audit says what is technically wrong with a storefront and scores it. A CRO audit is a strategist's argument about where conversion is being lost, and what comes out of it is the slides of a client deck: one per page type, three to five opportunities each, in the house `Short title: short description` format. It has its own list, its own report, its own share links, and it never mixes into a site-audit report.",
      "**It runs in two passes, split by what each one physically needs.** `barrel-audit cro <url>` drives a real browser from your machine: it walks the nav, home, collection, product and cart page types at a phone width and a laptop width, screenshots each one, and records what it measured. Then a **Generate** button on the finished audit runs here on the site — no browser, no terminal — reading the store's GA4 for the conversion picture and writing the four key insights across everything. A store with GA4 linked gets that half with no local setup at all.",
      "**Capturing and interpreting are separate on purpose.** The browser pass stores the evidence — screenshots, the signals read out of each page, and the fold and scroll measurements — as its own record. Every slide is then written from that record rather than from the live site, which is what lets a section be rewritten later without crawling a client's storefront again.",
      "**The measurements are the thing that makes a bullet worth reading.** \"The add-to-cart control sits 867px down, 23px below the first mobile screen\" is a sentence a developer can act on and a client can check. Where each section of the page starts, how many controls begin below the fold, how many tap targets are under 44px, and the contrast of the primary button all come out of the page itself.",
      "**The scroll figures are labelled as a proxy, not as behaviour.** They say what a visitor would have to scroll past. They do not say what any visitor did — that needs a heatmap tool, and the report says so rather than implying otherwise.",
      "**The deck format is enforced in code, not asked for in a prompt.** A bullet whose title runs past a slide, or opens by naming a fault (\"Missing trust signals\") instead of an opportunity, is discarded. So is any bullet carrying a figure that appears nowhere in the evidence it cited — the same rule the Data Analysis tab runs on. Discarded bullets are listed with the reason rather than dropped quietly, so a thin slide reads as a caught mistake and not as a thin finding.",
      "**The competitive benchmark leads with a grid, not with prose.** Which of fifteen features — subscriptions, quick add, size guide, instalments, a stated free-shipping threshold — each brand actually has, detected from their markup with no model involved. A tick means the feature was found on the site, not that it is implemented well, and the slide says that.",
      "**Every bullet is editable, and editing never rewrites the audit.** Corrections are saved as an overlay beside the generated record, which may already have been sent to a client. Bullets can be hidden from the deck rather than deleted. If a step is regenerated and an edit no longer matches any bullet, it is kept and flagged rather than silently discarded.",
      "**Deck view prints one 16:9 slide per page**, through the browser's own print dialog, so the PDF keeps selectable text. Share with client mints the same kind of signed 30-day link the site audit uses, scoped so it authorises that one audit's screenshots and nothing else.",
      "**Which product page gets reviewed is chosen by traffic where possible.** With GA4 linked it is the most-viewed product of the last 28 days, rather than whatever sorts first in the catalogue — which on a lot of stores is a gift card. The collection page is the largest published collection, not `/collections/all`, which many themes disable.",
      "**Checkout capture is off by default and says why.** Reaching checkout means adding a real item to a real cart on the client's live store, which leaves an abandoned checkout in their admin. It takes an explicit `--checkout`.",
      "**Three parts of the process are still done by hand, and the report says so on the page**: heatmaps and session recordings, the voice-of-customer review analysis, and the CX journey map. An empty section with no explanation reads as \"nothing to improve here\", which is never what it means.",
      "Each store now has a **CRO brief** — competitors, which analytics and heatmap tools the client actually has, business model, their own stated hypotheses. It is saved on the store so later audits reuse it, and each audit keeps a copy of the brief it was run against.",
    ],
  },
  {
    version: "1.31",
    date: "2026-08-20",
    title: "Barrel Google sign-in, and Privacy Compliance limited to admins",
    notes: [
      "**The shared site password is gone.** Sign-in now goes through Barrel Labs with your Barrel Google account — no password to look up, ask for, or rotate when someone leaves. Nothing here stores a password or a Google credential; Labs owns the sign-in and the access list, and hands this app a 60-second token it verifies against Labs' public key.",
      "**Access is managed in Barrel Labs, not in this tool.** Adding or removing someone is a change to the `site-audit` app's access list in Labs → Control, and it applies wherever this app is deployed. Removing access takes effect here within 8 hours rather than instantly — that is the length of this app's own session, and the tradeoff for the sign-in being invisible the rest of the time.",
      "**Privacy Compliance is now admins only.** It is a standing record of where client sites are, today, setting tracking cookies before a visitor consented — a live legal-exposure list about people who are our clients, which reads very differently out of context than a list of findings to fix. Only a Barrel Labs admin can open the dashboard, a site's privacy report, or start a bulk scan.",
      "**A member does not see a broken link.** The tab is left out of the nav rather than rendered and then refused, and anyone who follows an existing link keeps the URL they were sent and gets a page naming the gate and who lifts it. The refusal is enforced three times over — in middleware, in each page, and in the scan API — so a route added under Privacy Compliance later is closed by default.",
      "**The rest of the app is unchanged and open to everyone who can sign in**, including every store's audit report.",
      "**Everything the app serves is now behind sign-in**, the CLI instructions and this release-notes page included — both of those were readable by anyone under the old password login. Client share links are the deliberate exception and are unaffected: opening without a Barrel account is the whole point of them, and they carry their own signed, single-report, 30-day token rather than leaning on the session.",
      "The header now shows who you are signed in as, because which pages exist depends on it — a member wondering where Privacy Compliance went can read the answer off the nav instead of assuming the tool is broken.",
      "Signing out returns you to the Barrel Labs hub rather than back here, where a still-live Labs session would have signed you straight back in.",
    ],
  },
  {
    version: "1.30",
    date: "2026-08-20",
    title: "Data Analysis — the audit crossed with the store's own GA4 data",
    notes: [
      "**Reports for a store with a linked GA4 property now have a Data Analysis tab.** It pulls the last 28 complete days from GA4 — sessions, users, transactions, revenue, conversion rate and average order value overall, and the same figures split by device, by channel and by landing page — works out where conversion is weakest, and asks Claude to rank what to do about it against the findings already in the report. It runs entirely from the deployed site: no CLI, no browser, no local checkout.",
      "**The device and landing-page splits are the point.** Totals cannot tell you anything actionable: a 1.6% site-wide conversion rate is a fact about a blend. Mobile converting at a third of desktop's rate while carrying 71% of sessions is a place to go and look.",
      "**Every number on the page was computed here, not written by the model.** Recommendations cite evidence by id from a catalogue this tool builds out of the GA4 response and the report, and the page prints the catalogue's own wording. The model writes prose and chooses which facts to cite; it never supplies a figure.",
      "**A recommendation carrying a number that appears nowhere in the data it cited is discarded**, and listed as discarded with the offending figure named — so a filtered run cannot be mistaken for a quiet one. This is the check that catches the classic failure: *fixing this typically lifts mobile conversion 15–20%*, where nothing in the input contains 15 or 20.",
      "**No forecasts, anywhere.** Gap sizes are arithmetic on days that already happened — the weak segment's own sessions at the benchmark's rate, valued at the observed average order value — and are labelled as the size of a difference already measured, never as what a fix would earn. The model is forbidden from producing a projection and cannot smuggle one past the number check.",
      "**Correlation is not written up as cause.** The audit measured the site; GA4 measured behaviour. Joining the two is a hypothesis to test, and every recommendation that does it is marked *Hypothesis* and carries a note on what else could produce the same numbers. Only a restatement of what GA4 recorded is marked *Measured*.",
      "**Not enough data is said, not filled.** A property with fewer than 21 days of recorded sessions, no sessions at all, no transactions, fewer than 25 transactions, or transactions recorded without revenue gets a plain statement of which of those is true and no recommendations — and no Claude call is made at all, because there is nothing there to analyse and a model would produce something that read like analysis anyway. The figures are still shown, so the refusal can be checked.",
      "**The tab appears only when a GA4 property is linked.** A permanently empty tab reads as a broken feature rather than an unconfigured one.",
      "Missing credentials, a service account without access, a property that does not exist, and a GA4 API error each get their own message naming the thing to go and change — and none of them writes a half-finished analysis to storage.",
    ],
  },
  {
    version: "1.29",
    date: "2026-08-20",
    title: "Connect GA4 from the dashboard",
    notes: [
      "**A GA4 property can now be linked to a store from the Run Audit page**, next to the Traffic & Revenue check — which is where the question \"why is this box unticked?\" actually gets asked.",
      "**It verifies before it saves.** A property ID that is well-formed but never shared with the service account used to save without complaint and then produce an empty Traffic & Revenue section on every later run — which reads as *this store has no traffic*, not as *nobody granted us access*. One real query now turns that into an error at the moment someone can fix it, naming the service account to add and where to add it.",
      "Pasting a `G-` measurement ID or a stream ID is caught by name rather than rejected as malformed, because that is the mistake people actually make.",
      "**The GA4 check is now unticked by default and ticks itself only when a property is linked.** Leaving it on meant every run for an unlinked store carried a check that could only produce nothing.",
      "Where the service-account key is not deployed the property still saves, marked unverified rather than confirmed — refusing there would make the form unusable on exactly the instance most people open.",
    ],
  },
  {
    version: "1.28",
    date: "2026-08-20",
    title: "Which checks need the CLI, marked on the checks themselves",
    notes: [
      "**Checks that read HTTP responses only are now marked `Online`** on the Run Audit page — site health, SEO & GEO, agent readiness and GA4. No browser, no theme code, so they do not need a machine running the CLI.",
      "Everything else drives a real Chrome or reads the theme from disk: Lighthouse, axe, the pixel and consent checks, UX, screenshots and the theme code checks. The note says plainly what an online run gives up — it cannot answer whether a pixel actually stops when a visitor opts out, or what the site scores on mobile.",
      "Marked per check rather than explained in prose, so the answer sits next to the box being ticked.",
    ],
  },
  {
    version: "1.27",
    date: "2026-08-19",
    title: "The same audit, turned on the security section",
    notes: [
      "The adversarial pass that found six false passes in the consent scanner was run again against the security checks, with the same question asked of every finding: **what else could produce this, other than the fault it names?** Nine answers, and this time the worst ones ran in the other direction — findings the tool would raise against sites that had done nothing wrong.",
      "**A `/config.json` finding fired on any valid JSON.** The match condition was, in effect, \"does this parse\" — so `{}`, `{\"error\":\"not found\"}`, and any headless storefront whose catch-all answers unknown paths with a JSON 200 were reported at **critical**, described as matching the real file, and told to rotate every credential the client owns. It also tripped the score's critical-failure gate, taking a 64 to a 31 on that one probe. The check now requires secret-shaped content — a key like `password`, `token` or `api_key` carrying a real value, or a PEM private-key block — and says so in its own wording.",
      "**Nothing checked whether the homepage request had actually succeeded.** A Cloudflare challenge, a 429, a 503 or a Shopify password page flowed into all eighteen checks as though it were the store. Because an interstitial ships `x-frame-options`, `nosniff` and a `referrer-policy` of its own, **the storefront was credited with header controls it may not set anywhere**, while CSP, HSTS and every cookie flag were read off the edge's page. Those checks are now *not tested*, with the status code in the reason. TLS, the HTTP→HTTPS redirect and the file probes make their own requests and still report.",
      "**The jQuery check stopped at the first copy it could read.** A theme on 3.7.1 and an app dragging in 1.12.4 passed on the theme's copy — and a third copy was never fetched at all. It now reads every jQuery tag on the page and reports the oldest, which is the one that matters: a newer copy elsewhere does not remove the old one.",
      "**Clickjacking protection passed on a `<meta>`-delivered policy.** Browsers ignore `frame-ancestors` in a meta tag by specification, so that was a pass for a control no browser applies. It now requires the response header — and treats `https:` as the wildcard it is, matching what the CSP `script-src` check next door had always done.",
      "**`Permissions-Policy` passed on presence alone**, so `camera=*, microphone=*` — which grants exactly what sending no header grants — passed with the permissive policy printed underneath as its own evidence.",
      "**Cookie findings named cookies the site cannot change.** The list that correctly excuses `_ga` and `_shopify_*` from `HttpOnly` was wired to that one check; `Secure` and `SameSite` still failed storefronts over cookies Shopify and gtag set, with a fix instruction that has no place in the codebase to apply it. All three now separate what the site owns from what it merely carries.",
      "**Mixed content ignored `upgrade-insecure-requests`** — a directive the analyzer already read — and told clients their scripts were blocked on pages the browser silently upgrades and renders fine.",
      "**An incomplete certificate chain was reported as an outage.** Node stops where the served chain stops; every mainstream browser fetches the missing intermediate itself. \"Visitors reach an interstitial browser warning\" was a claim about a site that loads normally. It is now reported as what it is — a compatibility defect that breaks webhooks and API clients while the storefront looks healthy — and an error code the tool does not recognise no longer carries a claim about what a browser does with it.",
      "**The HTTP→HTTPS and exposed-file probes tested the wrong host.** They ran against wherever redirects had landed, so an apex serving plaintext passed on the strength of its canonical host's redirect. They now probe the hostname as it was given, and the finding says which hostname that was.",
    ],
  },
  {
    version: "1.26",
    date: "2026-08-19",
    title: "The rest of the audit's findings",
    notes: [
      "**A check that could only ever pass is now reported as untestable.** \"Banner returns after cookies are cleared\" returned 23 passes, 18 blocked and not one finding across 41 runs — and handed each of those 23 sites a free point. It cannot work in this design: every state opens a fresh browser context, which clears localStorage along with cookies, so a consent record that outlives the cookie cannot be told apart from one that does not.",
      "**Non-US storefronts were failed for missing a California opt-out link.** The check keyed off where the *scanner* ran, not who the store serves, so .fr, .de and .co.uk sites were marked down for it. Verified fixed on a French storefront.",
      "**Localised privacy links are now found.** Link matching was English-only against the light DOM, so a French footer reading \"Politique de confidentialité\" counted as no privacy policy at all, and an Osano-hosted link was invisible. It now reads aria-labels, walks shadow roots, and knows the common European wordings.",
      "**Cookie-cleanup findings now separate who can actually delete what.** Telling a client to clear MUID on .bing.com is an instruction nobody can carry out, and the `_shopify_*` cookies are Shopify\'s own. All three used to be listed under one fix, which is how a real finding gets filed as noise.",
      "**The GPC comparison was measuring two different-length windows** — 3 seconds for the baseline against 8 for the probe — so a tag that fires on a delay could get a site accused of specifically ignoring the signal purely because of the timing. Klaviyo, which fires late and appears in 30 of 38 recorded pre-consent findings, is exactly that profile.",
      "**Shopify consent is now read back rather than assumed.** The adapter reported success because setTrackingConsent existed, resolving on a three-second timer even when Shopify silently dropped the payload — producing a \"rejection\" nobody made, in which every tracker naturally looked blocked.",
      "A two-letter cookie name no longer counts as a Meta signature: a locale cookie called `fr` was enough to raise a blocker on a French store.",
    ],
  },
  {
    version: "1.25",
    date: "2026-08-19",
    title: "An adversarial audit of the scanner, and the false passes it found",
    notes: [
      "An agent was set one question against every check: **what could produce this finding other than the fault it names?** It found six ways the tool could wrongly clear a site — the class that matters, because a finding wrongly raised wastes an afternoon and a finding wrongly suppressed ships a site that is leaking data with a clean bill of health.",
      "**The flagship test could not see the most common tag on the web.** The reject state never reloaded after the choice, so it only ever noticed tags that beacon again on their own. A page-view pixel had already fired during the pre-choice load and had nothing left to send. Across 23 storefronts the pre-consent check named Meta Pixel 23 times and the after-reject check named it zero times — and five of eleven clean passes sat on captures where Shopify still reported marketing as allowed, meaning the rejection had never been recorded at all. The state now reloads before reading. Both sites retested went from pass to fail.",
      "**A missing banner could pass the banner test.** OneTrust and Shopify both defaulted to \"yes, a banner is showing\" when the element was absent, so a storefront that prompts nobody passed a blocker-severity check. On 10 of 23 of those passes the very next test reported no accept control anywhere on the page.",
      "**The dismissal suite had never produced a result** — 0 passes and 0 failures across every recorded run. Its success condition asked the CMP whether the visitor had answered, which cannot change when the whole point is closing the banner without answering. It now checks whether the banner is still painted.",
      "**Library downloads were being reported as tracking.** 16 of 18 \"Google Analytics 4 fired before consent\" findings cited nothing but the gtag library — which under a correct Consent Mode setup is supposed to load early so it can receive the denied default. The report was telling clients to undo what they had done right.",
      "**Stock CMP button labels were unmatchable.** OneTrust ships \"Accept All Cookies\" and Cookiebot \"Allow all cookies\", and neither matched. The dark-pattern check was silently skipped on 20 of 41 runs, and on a banner reading \"Use necessary cookies only\" it accused the site of offering no reject control at all.",
      "**\"Console errors from the CMP\" was still wrong in a second place.** The same defect fixed in A4 was live in A1 at ten times the scoring weight: for a Shopify storefront the vendor filter was the word \"shopify\", so an analytics beacon failing to reach Shopify\'s own logging endpoint failed a site at blocker severity and told it a domain-group ID had expired. Errors are now matched on each vendor\'s script hostnames.",
      "**New: the unwired-CMP diagnosis.** Where a vendor CMP records the rejection and Shopify does not hear about it, the report now names the likely cause — the vendor\'s script is installed but its Shopify app is not, so nothing calls setTrackingConsent(). Everything registered as a Customer Event keeps firing while the banner visibly responds, which is what makes it easy to miss.",
    ],
  },
  {
    version: "1.24",
    date: "2026-08-19",
    title: "Compliance scores get their own colour scale",
    notes: [
      "**60+ healthy, 30+ improving, below 30 at risk** — a deliberately different scale from the Lighthouse-derived scores elsewhere in the app, which turn green at 90.",
      "Two reasons it needs its own. A compliance score is a weighted proportion of what was actually confirmed, not a percentage of a fixed total, so a 40 there is not the claim a Lighthouse 40 is. And a confirmed blocker scales a site into the bottom half by design — which means **a site with an unresolved blocker mathematically cannot reach green**. That is the intended reading: nothing that leaks data after an opt-out should present as healthy.",
      "The cutoffs are set to be reachable. Full marks is not a realistic target for a live storefront running a marketing stack, and a scale where every site is red teaches people to ignore the number.",
    ],
  },
  {
    version: "1.23",
    date: "2026-08-19",
    title: "Untested no longer looks like clean",
    notes: [
      "**A section where nothing could be tested was showing green.** \"Opt-out effectiveness — nothing observed — 8 unproven\" rendered as a pass, on a site where the opt-out flow had never been driven at all. Green on the opt-out section of a compliance report, for a site whose opt-out was untestable, is the worst misread this report can produce.",
      "There are now three states rather than two: findings, **no findings** (checks ran and passed), and **not established** (nothing could be confirmed either way) — the last in amber, with a line saying to read it as untested rather than clean.",
      "**The same conflation was in the fleet table.** A site was marked Clean unless *nothing at all* passed or failed, so one confirmed result alongside two dozen blocked ones showed green. Clean now requires that enough was confirmed to say so, keyed off the same definition the score already uses rather than a second threshold that could drift from it.",
    ],
  },
  {
    version: "1.22.1",
    date: "2026-08-19",
    title: "Two findings that were the tool's fault, not the site's",
    notes: [
      "**\"Console errors from the CMP\" was counting every error on the page.** It fired on 17 of 23 sites, and across all of them not one cited error came from a consent platform — they were undefined theme variables, 404s and minified React warnings. Real errors, wrong culprit, and a recommendation that talked about CMPs failing open. It now separates errors by origin and says plainly when none came from the CMP. A finding a developer can disprove in ten seconds costs more than it is worth, because the next one gets disbelieved with it.",
      "**The Global Privacy Control check was double-counting.** It failed on 18 sites and every one of them had already failed the pre-consent check — it produced no independent signal at all, while adding a second finding to the sites least able to afford one. The cause: the probe makes no consent choice, so on a site that transmits before anyone chooses, it transmits under GPC too — for that reason, not because the signal was ignored.",
      "GPC is now judged as a difference rather than a snapshot. Where a site gates tags for everyone else and not for GPC, that is still a finding. Where it gates for nobody, the report says the signal changed nothing and points at the shared root cause, so it reads as one piece of work instead of two.",
    ],
  },
  {
    version: "1.22",
    date: "2026-08-19",
    title: "Automated tests, a build gate, and two bugs they caught",
    notes: [
      "**130 tests, and the build now refuses to proceed without them.** `pnpm check` runs the git-safety script, a formatting check, lint, typechecking across all three packages, and the suite — about ten seconds — and `pnpm build` runs it first. The tests are hermetic: nothing opens a socket or launches a browser, so they cannot be flaky for environmental reasons.",
      "**Drift guards for the duplicated code.** `web/lib/shared.ts` is a hand-maintained copy of the shared types, and two more copies existed that nobody was watching — the run-argument builder and the blob paths. All three now fail the build when they diverge, naming which side is missing what. The mirror had already drifted.",
      "**Caught: suite H findings were silently losing their evidence.** The map from test suite to browser state still stopped at G, so the dismissal tests — including \"closing the banner is not consent\" — dropped their screenshots. Retyped so the next new suite is a compile error until it is named.",
      "**Caught: two checks claimed things about pages that never loaded.** The privacy-policy and Do-Not-Sell checks read the page capture directly instead of through the guard, so on a site that timed out they reported \"no privacy policy link was found\" as a finding. That is the coverage-gap-as-failure conflation the whole report is built to avoid, and it is now impossible: a test asserts that *nothing* can fail when nothing was reached.",
      "**Self-healing has a hard boundary.** It retries a failing test, reports anything that only passed on retry as flaky rather than passed, and auto-fixes formatting and lint. It will never modify, soften, skip or regenerate an assertion — a harness that hides failures is worse than no harness. It also stands down entirely in CI.",
      "Results land in `test-results/` as JSON and a readable summary.",
    ],
  },
  {
    version: "1.21",
    date: "2026-08-19",
    title: "New: Security & Compliance",
    notes: [
      "**Every report now has a Security & Compliance section.** It checks the security headers (`Content-Security-Policy` — present *and* whether its `script-src` actually restricts anything, `Strict-Transport-Security` and its `max-age`, `X-Content-Type-Options`, clickjacking protection, `Referrer-Policy`, `Permissions-Policy`), transport (HTTP→HTTPS redirect, mixed content, TLS certificate validity and days to expiry), the flags on every cookie the homepage sets, four commonly-leaked paths, published source maps, server version disclosure, missing subresource integrity on third-party scripts, and the jQuery version.",
      "**Every finding shows the header value, cookie name or URL it was read from.** A security claim a client's own engineer cannot re-check with one `curl` is worth nothing, and one that turns out to be wrong discredits the rest of the report with it.",
      "**A check that could not be run says so, as its own state.** \"Not tested\" is never rounded into a pass or a fail, and is excluded from the score entirely — so a site we could not fully reach cannot out-rank one we could.",
      "**No guessing, deliberately.** Exposed-file checks only fire when the response body actually matches that file's format, because a great many hosts answer `/.env` with a 200 and their own homepage — a naive scanner reports a critical breach on a perfectly healthy store. Source maps are only reported once the map has actually been fetched. The jQuery version is read out of the library file rather than off its filename, and the only advisory named is the one that fixed 3.5.0.",
      "**It adds about two seconds.** No browser: everything comes from HTTP responses, the delivered HTML and one TLS handshake. Skip it with `--skip-security`.",
      "**Scored like Privacy Compliance** — a weighted proportion of what was actually confirmed, no score at all when too little was, and any critical failure scales the section into the bottom half so a readable `.env` can never present as a passing grade.",
    ],
  },
  {
    version: "1.20",
    date: "2026-08-19",
    title: "A report you can actually send a client",
    notes: [
      "**New: the client report** at `/client-report/<store>`, reachable from any store in Baseline & Reporting. One page, written for the client rather than the developer: overall score against baseline, the homepage side by side then and now, what moved in each area, and the three or four things worth doing next.",
      "**It leads with progress, not problems.** Where a site has improved the report says so and names the biggest gain, because a document that only lists faults reads as a bill rather than as work delivered. The issues it does raise are framed by what fixing them wins.",
      "**Deliberately capped at four issues.** A list of forty findings is a document nobody acts on; three or four is a conversation, and the full audit is still there for the detail.",
      "**Shareable on the existing link machinery** — signed, 30-day expiry, view-only, no login. Extended so one link can authorise both reports it shows: a client link that renders the baseline screenshot as a broken image would undermine the whole point.",
      "Print-styled, so Save as PDF produces something you can attach to an email.",
      "An area missing from the baseline is left out of the comparison rather than counted as zero — inventing a dramatic gain from a measurement that never happened is the fastest way for a client to stop believing the rest of it.",
    ],
  },
  {
    version: "1.19",
    date: "2026-08-19",
    title: "A real top navigation",
    notes: [
      "**One navigation, defined once.** Every page carried its own header with an ad-hoc list of links, so each new surface either got forgotten or made the row longer until the buttons at the end started wrapping. Reports, Privacy Compliance, Baseline & Reporting and CLI Instructions now live in a shared nav with active-state highlighting, and the current section stays lit on its sub-pages.",
      "**A page's title no longer competes with the nav for the same 73px.** Titles and page-specific actions moved to their own row underneath, which is what makes room for the next destination without another redesign.",
    ],
  },
  {
    version: "1.18",
    date: "2026-08-19",
    title: "Privacy Compliance — closing the banner, chat widgets, and load order",
    notes: [
      "**New: closing the banner is tested as its own state.** Dismissing a notice is not agreement, but plenty of CMPs wire the X to accept and start transmitting on a choice the visitor never made. Nothing else in the scan could see it. Two new tests (H1, H2) drive the close control — or Escape — and assert that nothing fired and no consent was recorded. A banner offering no way to dismiss is reported as such rather than as a failure: forcing a choice is the safer design.",
      "**Chat widgets and session-replay tools are now catalogued** — Intercom, Drift, Gorgias, Zendesk, Tidio, Tawk, FullStory, LogRocket, Smartlook, Mouseflow, Lucky Orange. Sharper exposure than a page-view pixel, because they capture what a visitor typed rather than which page they saw.",
      "**New: does the CMP load before the tag manager?** (A5) A CMP that loads second cannot gate what the tag manager has already fired, however correct its configuration.",
      "**New: is a GPC opt-out visibly confirmed?** (G5) California has required a visible confirmation since January 2026 and Colorado has a parallel rule, so honouring the signal silently now satisfies only half of it.",
      "**The opt-out link is checked on a second page**, not just the one scanned. A footer link present on the homepage and missing from a collection page meets the requirement in appearance rather than in fact.",
      "**The per-site report now groups findings by exposure** — tracking before consent, opt-out effectiveness, browser signals, notice and reachability, and tags not firing when permitted. The suites are ordered by when something was tested, which is right for running the scan and wrong for reading it.",
    ],
  },
  {
    version: "1.17",
    date: "2026-08-19",
    title: "Privacy Compliance — marketing interstitials can no longer be mistaken for the consent banner",
    notes: [
      "**A false pass was possible on the one test that matters most.** The scanner found consent controls by matching button text anywhere on the page. An email-capture popup offers \"No thanks, continue without discount\" and \"OK\" — which matched the reject and accept patterns. Clicking one reported success, and the scan then measured a \"rejected\" state in which nobody had rejected anything, where every tracker naturally looked correctly blocked.",
      "**Consent controls are now found only inside consent UI.** A match must sit within a container that talks about cookies, privacy or tracking, and must not sit inside a known marketing popup — Klaviyo, Attentive, Privy, Justuno, OptinMonster, Wisepops, Omnisend, Postscript. A positive requirement rather than a blocklist: a consent banner always mentions cookies, and a discount modal never does.",
      "**Every consent choice is now confirmed before the state is measured.** If the banner is still showing afterwards, the click did not reach the CMP and the state is reported `blocked` rather than treated as a rejection. A mis-click can no longer present as consent working.",
      "**Interstitials are disclosed rather than silently absorbed.** When a marketing modal is covering the page, the per-site report names it and says why it matters — it can sit over the consent banner, and its own vendor's tags load with it.",
      "Verified against four storefronts with live email-capture popups: no state became untestable, and the genuine post-rejection leak on one of them is still caught.",
    ],
  },
  {
    version: "1.16",
    date: "2026-08-19",
    title: "Privacy Compliance — a score that actually ranks anything",
    notes: [
      "**Every site was scoring 0.** The old score subtracted a flat penalty from 100 with a blocker costing 35, so three blockers floored a site at zero — and most storefronts have three. A site passing nineteen tests and one passing two were indistinguishable. Across a 23-site fleet, 21 scored exactly 0.",
      "The score is now a **weighted proportion of the tests that applied and were confirmed**. A site showing no banner has fourteen inapplicable tests, and judging it out of a fixed 100 marked it down for questions that were never asked.",
      "**Unknown is not half-good.** Flaky and blocked results are excluded from both sides of the ratio instead of earning partial credit. Modelling this against the real fleet caught the alternative red-handed: crediting them put the one site we had entirely failed to load at the *top* of the ranking.",
      "**A confirmed blocker always shows.** Any blocker-severity failure scales the result into the bottom half, so \"leaks data after opt-out\" can never present as a passing grade — while still separating one blocker from four.",
      "**Sites with too little confirmed are marked `n/s`, not 0.** A number there rates the site when it should rate the coverage. Those sites are also skipped in the overall report score rather than counted as a zero.",
      "On the same fleet the range is now 1–40 with sensible ordering: Waterloo 34, Wamsutta 11, Pavise 1, and the two sites nobody could test marked not-scored.",
    ],
  },
  {
    version: "1.15",
    date: "2026-08-19",
    title: "Privacy Compliance — separating \"the script loaded\" from \"data was sent\"",
    notes: [
      "**A blocker now means data actually left the browser.** Downloading `connect.facebook.net/en_US/fbevents.js` is fetching a library; sending `facebook.com/tr?id=…&ev=PageView` is telling Meta about the visitor. The scan reported both as \"the pixel fired\" — which hands a client's developer a blocker they can correctly dismiss, and once one blocker is dismissed the genuine ones go with it. Every blocker-severity test now reads transmissions only.",
      "**Script loads are still reported, at warning severity** (new B5 and C5), stating the weaker claim honestly: the vendor learns an IP address and a referring URL, which some readings of GDPR treat as a transfer in itself. Anthony's Goods is the shape of it — Meta, Google and Klaviyo genuinely transmitted pre-consent, while TikTok had only fetched its script.",
      "**Findings now quote the identifying parameters**, so a claim proves itself: `px.ads.linkedin.com/db_sync (pid=12608, gdpr=0)` rather than a bare URL buried in a hundred query parameters.",
      "**A request that never arrived no longer counts as a fire.** Responses are tracked, not just requests, so a tag the CMP aborted stops reading as a tag that leaked. A 4xx still counts — the vendor received it and answered.",
      "**Passing opt-out results are now confirmed by a second pass.** \"Nothing was transmitted after the visitor opted out\" is a negative claim, and one observation is thin evidence for a negative. A tag firing on nine loads in ten produced a clean pass on the tenth. Found immediately: one site's Klaviyo transmits after rejection intermittently, and is now reported flaky rather than confidently passed.",
      "Two classifier bugs fixed in the process — `analytics.tiktok.com/i18n/pixel/events.js` was read as an event because its path contains \"pixel\", and Klaviyo's web fonts and geo-IP lookup were counted as tracking.",
    ],
  },
  {
    version: "1.14",
    date: "2026-08-19",
    title: "Privacy Compliance — bulk scanning and a report you can hand to a client",
    notes: [
      "**New: a comprehensive per-site report** at `/consent/<site>`, reachable from any row in the fleet table. It leads with a tag × consent-state matrix that answers the question clients actually ask — *I opted out, did Meta stop?* — as an explicit **OK / FAIL / Silent** verdict for every tag under every choice, rather than a colour you have to decode.",
      "**Silent is its own verdict.** A tag that stays down when the visitor permitted it isn't a compliance problem, it's a destroyed-attribution problem — and a report that only looks for over-firing never finds it.",
      "Below the matrix: every test with its status, detail, fix and evidence; then each state's cookies, Consent Mode signals, Shopify Customer Privacy state and banner screenshot. **Print → Save as PDF** is styled for it, so the PDF keeps selectable text and live links instead of being a screenshot.",
      "**New: bulk scanning** at `/consent/run`. Paste any number of URLs or slugs — one per line or comma-separated, bare domains fine — and scan them independently of the per-store audit, with the CLI's output streaming live. `consent-scan` now takes as many targets as you pass on the command line too, and collapses duplicates. A bare domain like `blueair.com` is understood as a site rather than rejected as a missing registry slug — which is how a pasted column of domains actually arrives.",
      "Scanning drives a real browser, so it runs from a local checkout. On the deployed site that page becomes a **command builder** rather than a dead button — paste the list, copy the exact invocation, run it locally. Results publish to Blob either way, so the deployed dashboard shows them the moment the scan finishes.",
      "Per-site detail is stored as its own blob rather than folded into the fleet payload, so the table everyone opens doesn't pay to load the cookie lists and evidence almost nobody scrolls to.",
    ],
  },
  {
    version: "1.13",
    date: "2026-08-19",
    title: "Privacy Compliance — renamed, and taught the difference between broken and by-design",
    notes: [
      "**Consent QA is now Privacy Compliance**, in the report section, the dashboard page and the nav. Same tests, a name that means something to a client. The `/consent` URL is unchanged, so existing links still work.",
      "**The fleet view is now a table.** One row per site, sorted worst-first, with status, score, blocker count and the failing test IDs as chips you can hover for the detail — built to stay readable at fifty sites rather than four.",
      "**New: fixes that span more than one site.** Any failure appearing on two or more sites is rolled up with the list of sites and the remediation, because six sites failing the same test is one piece of work, not six.",
      "**Fixed a false positive that flagged correct implementations.** A Google tag that has been denied consent still calls home — cookieless, carrying `gcs=G100` — precisely to report the denial. The scanner counted that as \"marketing fired after reject\" and raised a blocker on sites doing exactly the right thing. It now reads the Consent Mode state on each request, so a denial is scored as a denial.",
      "**Fixed Osano banner detection.** Osano keeps a fully-rendered banner hidden in the page under an implied-consent configuration, so the old check reported a banner on sites that prompt nobody — passing the banner test and then failing to explain why nothing could be clicked.",
      "**\"We could not test this\" no longer looks like \"this failed.\"** Where a CMP reports an implied-consent model, the choice-driven suites are marked not-applicable with the vendor's own jurisdiction quoted, instead of 14 blocked results. Inferred only from the CMP's own configuration — a banner that is merely broken still reads as a coverage gap.",
      "**Hardened for large fleets.** Every browser state now runs under a hard deadline so one hung page cannot stall a scan, and a failed browser connection can no longer leak a Chrome process per site.",
    ],
  },
  {
    version: "1.12",
    date: "2026-08-19",
    title: "Consent QA — testing whether consent actually works",
    notes: [
      "New `consent-scan` command and a **Consent QA** section in every report. It drives the cookie banner for real — reject, accept, analytics-only, returning visitor — each in its own fresh incognito browser, and checks that trackers genuinely stop and start. 25 tests across 7 suites.",
      "This replaces the only consent check we had, which was a regex looking for the word \"cookiebot\" in the page source. A banner that renders but blocks nothing passed that check; it fails almost everything here.",
      "The new **Consent QA** page lists every client site, worst first, with the failing test IDs and the actual request URLs behind them. Run `pnpm barrel-audit consent-scan` to populate it.",
      "It tests that accepting works too, not just that rejecting does. A banner that blocks everything forever looks perfectly compliant and is quietly destroying the client's attribution — that's test D1.",
      "Findings distinguish \"failed\" from \"blocked\". A site that was down or never showed its banner is reported as untested, never as non-compliant — you can trust a clean result to mean something.",
      "Blocker-severity failures are automatically re-run once to confirm before being reported, and anything that disagrees between the two runs is marked flaky rather than stated as fact.",
      "Speaks Cookiebot, OneTrust, Osano, CookieYes and Shopify's Customer Privacy API, preferring each vendor's own JS API over clicking buttons. An unrecognised banner falls back to matching \"Reject\"-style button text, so a newly swapped CMP still gets tested instead of silently dropping out of coverage.",
      "Which sites get scanned lives in `sites.yml` at the repo root — `consent-scan --seed` drafts it from your existing stores. See docs/consent-qa.md for the full test plan.",
      "It reports technical behaviour, not legal compliance. \"Meta Pixel fired before consent\" is a fact; what it means under a given law is counsel's call, and the report says so.",
    ],
  },
  {
    version: "1.11",
    date: "2026-08-18",
    title: "Stop audit, and no more silently code-less reports",
    notes: [
      "\"Stop audit\" on the run progress screen now genuinely stops the run — it asks to confirm first, then kills the CLI and every headless browser it opened on your machine, and the screen says the run was stopped by you rather than pretending it finished.",
      "Two bugs behind that: stopping a run started through the local agent never actually stopped anything, and a stopped run left the \"an audit is already running\" lock stuck, refusing every later run until the process was restarted. Both fixed.",
      "New \"Theme code location\" box on the Run Audit form: point it at a local theme checkout (the folder with layout/theme.liquid) and the audit reviews that code. Saved per store, so you enter it once. Previously the only way to do this from the dashboard was to have already pulled the theme into the tool's own folder — the CLI's \"audit the theme I'm standing in\" shortcut can't work from the dashboard, which is why runs came back with no code findings.",
      "If \"Theme code & structure\" is checked and there is no code to review, the run now stops in the first second and says exactly how to fix it, instead of running for minutes and returning a report whose theme sections are simply missing — which read as \"nothing to flag\".",
      "Same check catches pointing at the wrong folder: if the path has no layout/theme.liquid, it says so, and suggests the subfolder if your repo keeps the theme one level down.",
      "When a run fails, the reason is now shown on the failure screen instead of only inside the collapsed CLI output.",
      "Fixed the globally-installed CLI mistaking a client repo for the tool's own: any repo with a `pnpm-workspace.yaml` (plenty of Shopify themes have one) was treated as the barrel-site-audit checkout, so it looked for `.env` and `stores/` inside the client repo and stopped with \"BLOB_READ_WRITE_TOKEN is not set\" even though `~/.barrel-audit/.env` had it. It now checks the repo is actually barrel-site-audit.",
    ],
  },
  {
    version: "1.10",
    date: "2026-08-18",
    title: "Run progress takes over the screen",
    notes: [
      "Starting an audit now opens progress as a full-screen modal instead of a panel below the form — the elapsed timer, current stage and rotating fact, with the page behind it dimmed and locked so there's nothing to accidentally edit mid-run.",
      "While the run is going there's no close button, just \"Cancel run\", which actually stops it — an X there would have hidden a run that was still going. Once it finishes, the modal turns into the outcome (complete or failed, with \"View report →\") and an X appears; Escape and a click outside work too.",
      "Closing it leaves the CLI output and report link on the page, so nothing is lost by dismissing it.",
      "Long theme-preview URLs no longer fill the heading with query-string tokens — it now reads \"Auditing client-store.com (preview link)…\".",
    ],
  },
  {
    version: "1.9",
    date: "2026-08-18",
    title: "ADA Scope Checker",
    notes: [
      "Paste a client's scoped accessibility requirements into the new \"ADA scope\" field on the Run Audit form (or pass `--ada-scope-file`), and the report checks off each line against what the audit actually measured — axe-core, Google Lighthouse's accessibility audit, and a live pass that presses real TAB keys through every journey page.",
      "The ADA tab leads with that checklist: a ticked box means an automated check verified the line; anything else carries a developer-ready action naming the failing elements, on which page, and what to change. Outstanding items also flow into the prioritized roadmap and Dev To-Do list.",
      "The live pass catches what a rule engine can't: controls TAB never reaches, focus outlines that never appear, and whether the skip-navigation link exists, points somewhere real, and actually shows itself when focused. Consent-dialog focus traps are called out as the trap they are, rather than as a page full of unreachable controls.",
      "Two copy buttons on the section: \"Copy client update\" for a plain-English summary a PM or AM can paste straight into a client email (with the Lighthouse accessibility score), and \"Copy dev actions\" for the developer version with selectors and fixes.",
      "Scope wording varies client to client, so nothing is hardcoded: common phrasings are keyword-matched, Claude maps anything unfamiliar, and requirements no automated test can settle — captions, a screen-reader pass, zoom/reflow, PDFs — are labelled as manual checks with instructions for how to verify them, plus a checkbox you can tick yourself. The scope is saved to the store, so re-running an audit re-checks the same list.",
    ],
  },
  {
    version: "1.8",
    date: "2026-08-17",
    title: "Run the local agent from any folder",
    notes: [
      "`barrel-audit serve` — the local agent that lets the hosted dashboard trigger audits on your machine — now works from any directory, not just a barrel-site-audit checkout. Sit in a client theme repo and start it there; stores and reports fall back to `~/.barrel-audit/` as `run` already did.",
      "Reminder on the command itself: with the CLI installed globally it's `barrel-audit serve`, with no `pnpm` in front. `pnpm barrel-audit serve` only resolves inside this repo, and in a Shopify theme folder (no package.json) it fails with ERR_PNPM_NO_IMPORTER_MANIFEST_FOUND.",
      "Running an audit from inside a Shopify theme checkout now audits that code automatically — no `--local-repo .` needed. It looks for `layout/theme.liquid`, searching up from the current directory, and only applies when the store has no theme code of its own, so managed stores are never overridden.",
      "`run` now checks for the credentials it needs before starting, so a missing BLOB_READ_WRITE_TOKEN fails in a second instead of after several minutes of Lighthouse and browser passes. A missing ANTHROPIC_API_KEY is called out up front too.",
      "Every \"run this command next\" hint the CLI prints now matches how you actually installed it, instead of always saying `pnpm barrel-audit ...` even on a global install.",
      "Starting the agent on a port that's already busy now prints a one-line explanation and a suggested `--port`, instead of a raw Node EADDRINUSE stack trace.",
    ],
  },
  {
    version: "1.7",
    date: "2026-08-14",
    title: "Audit a repo you already have cloned, and a simpler CLI command",
    notes: [
      "`run --local-repo <path>` reads theme code straight from an existing local git checkout instead of copying it into stores/<slug>/theme/ — the fit for a dev auditing their own working copy rather than a client store managed via `link-repo`/`pull-theme`.",
      "For those stores, \"Suggest fix\" gets a fourth, simpler delivery option: write the change directly into that checkout, unstaged — no clone, no branch, no PR. Review and commit it yourself.",
      "The CLI can now be installed globally from GitHub Packages (`npm install -g @barrel/site-audit-cli`) and run from any directory, with config/report state falling back to `~/.barrel-audit/` when there's no barrel-site-audit checkout on disk.",
      "`pnpm run audit <url>` is now a shorter alias for `pnpm barrel-audit run <url>`.",
    ],
  },
  {
    version: "1.6",
    date: "2026-08-13",
    title: "Three ways to deliver a suggested fix",
    notes: [
      "\"Suggest fix\" now offers three independent choices instead of one: open the change in VS Code on a local branch, test it live with `shopify theme dev`, or push a branch and open a GitHub PR — pick any, none commit or push until you choose to.",
      "The VS Code and live-preview options share one prepared local branch, so edits made in the editor carry through if you then push.",
    ],
  },
  {
    version: "1.5",
    date: "2026-08-13",
    title: "About badge & release notes",
    notes: [
      "A small ⓘ badge in the header (landing page, report pages, and shared report links) explains how a report is generated, in plain terms — for anyone checking that the numbers are real.",
      "This page: a running, versioned changelog of what's shipped.",
    ],
  },
  {
    version: "1.4",
    date: "2026-08-13",
    title: "Broader structured-data scanning",
    notes: [
      "Site Health's structured-data check now reports the actual schema.org types found (e.g. \"Organization, WebSite, BreadcrumbList\") instead of just counting JSON-LD blocks.",
      "GEO now separately checks for Organization, WebSite, and BreadcrumbList structured data — not just Product/Offer — each with a concrete snippet to add if missing.",
    ],
  },
  {
    version: "1.3",
    date: "2026-08-13",
    title: "AI-suggested code fixes, report archiving, and a friendlier run screen",
    notes: [
      "Dev To-Do items that point at a real theme file get a \"Suggest fix\" button: Claude drafts a fix grounded in the real file and Shopify's Theme Check engine, you review the diff, and only on approval does it open a GitHub pull request — never merges anything itself.",
      "Reports can be archived/unarchived from the landing page or the report itself, without affecting Baseline & Reporting history.",
      "\"Progress\" renamed to \"Baseline & Reporting\" for clarity.",
      "The Run Audit wait now shows an elapsed timer, the current stage, and a rotating fact instead of a raw log.",
      "Fixed full-page screenshots coming out with gray placeholder boxes on pages with lazy-loaded sections.",
    ],
  },
  {
    version: "1.2",
    date: "2026-08-13",
    title: "Run audits from the dashboard",
    notes: [
      "A \"+ Run Audit\" form lets you kick off an audit by checking boxes instead of typing CLI flags, with the CLI's own output streamed live into the page.",
      "`pnpm barrel-audit serve` starts a local agent so this also works from the deployed dashboard, not just a locally-running copy of the site — the browser talks to it directly, gated by a one-time token.",
    ],
  },
  {
    version: "1.1",
    date: "2026-08-13",
    title: "Sitespeed.io, agent readiness, theme architecture, sharing, and progress tracking",
    notes: [
      "Added sitespeed.io as a second, independent performance signal (opt-in), an Agent Readiness section (per-SKU schema/hydration checks for AI shopping agents), and an AI-written Theme Architecture assessment.",
      "Reports can be shared via a private, expiring link — no login required for the recipient.",
      "Every report section now shows its own health-rating badge.",
      "Added Lighthouse's new Agentic Browsing category.",
    ],
  },
  {
    version: "1.0",
    date: "2026-08-11",
    title: "Initial release",
    notes: [
      "The barrel-audit CLI: Lighthouse performance/accessibility/SEO, axe-core accessibility, live site health checks, marketing-pixel & consent auditing, Shopify Theme Check code quality, an AI-written executive summary, and GA4 traffic/revenue and competitor benchmarking.",
      "A password-gated Next.js dashboard, deployed to Vercel, reading straight from Vercel Blob storage so a new report appears the instant a CLI run finishes.",
    ],
  },
];

export const CURRENT_VERSION = RELEASE_NOTES[0].version;
