import { notFound } from "next/navigation";
import { getReport } from "@/lib/data";
import { verifyShareToken } from "@/lib/share";
import { ReportHeader } from "@/components/ReportHeader";
import { ReportNav } from "@/components/ReportNav";
import { AboutBadge } from "@/components/AboutBadge";
import { buildReportSections } from "@/lib/build-report-sections";
import { ClientReport } from "@/components/ClientReport";
import { formatDate } from "@/lib/format";

export const dynamic = "force-dynamic";

export default async function SharedReportPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;
  const payload = await verifyShareToken(token);
  if (!payload) notFound();

  const report = await getReport(payload.slug, payload.id);
  if (!report) notFound();

  // A client link carries the summary, not the full audit. Same token machinery, same expiry,
  // same screenshot scoping — only the rendering differs.
  if (payload.kind === "client") {
    const baseline = payload.compareId ? await getReport(payload.slug, payload.compareId) : null;
    return (
      <div className="min-h-screen bg-[#f9f8f6] print:bg-white">
        <header className="bg-white border-b border-[#E5E5E5] px-6 lg:px-8 py-4 print:hidden">
          <div className="max-w-[1000px] mx-auto flex items-center justify-between gap-3">
            <span className="text-sm font-semibold text-[#1A1A1A]">Barrel Site Audit</span>
            <span className="text-[11px] text-[#9A9A9A] text-right">
              Shared report — view only
              <br />
              Link expires {formatDate(new Date(payload.expires).toISOString())}
            </span>
          </div>
        </header>
        <main className="max-w-[1000px] mx-auto px-6 lg:px-8 py-8 print:px-0 print:py-0">
          <ClientReport baseline={baseline} latest={report} />
        </main>
      </div>
    );
  }

  const sectionDefs = buildReportSections(report);

  return (
    <div className="min-h-screen bg-[#f9f8f6]">
      <header className="bg-white h-[73px] border-b border-[#E5E5E5] flex items-center px-6 lg:px-8">
        <div className="max-w-[1600px] w-full mx-auto flex items-center justify-between gap-3">
          <h1 className="text-2xl font-semibold text-[#1A1A1A] tracking-tight">Barrel Site Audit</h1>
          <div className="flex items-center gap-3">
            <div className="text-[11px] text-[#9A9A9A] text-right shrink-0">
              Shared report — view only
              <br />
              Link expires {formatDate(new Date(payload.expires).toISOString())}
            </div>
            <AboutBadge />
          </div>
        </div>
      </header>

      <main className="max-w-[1600px] mx-auto px-5 lg:px-8 pb-16">
        {/* No history links here — they point at authenticated /reports/... routes. */}
        <ReportHeader report={report} slug={payload.slug} history={[]} />
        <ReportNav sections={sectionDefs.map(({ id, label }) => ({ id, label }))} />
        <div className="space-y-0">
          {sectionDefs.map((def, i) => (
            <div key={def.id}>{def.render(String(i + 1).padStart(2, "0"))}</div>
          ))}
        </div>

        <footer className="mt-12 pt-5 border-t border-[#E5E5E5] text-[11.5px] text-[#9A9A9A] leading-relaxed">
          <b className="text-[#6B6B6B]">Methodology.</b> Performance and vitals figures are a single live Lighthouse
          (mobile) run against the storefront, not the throttled public PageSpeed API — lab data, not real-user field
          data. Site health, pixel/consent, theme code, and theme structure checks are static/live analysis of the
          same live storefront and its theme source. The roadmap is synthesized by severity across every section in
          this report, regardless of which page it's shown on.
          {report.aiUsage && (
            <>
              {" "}
              <b className="text-[#6B6B6B]">AI usage.</b> The executive summary, UX opportunities, and AI
              performance/accessibility suggestions above were generated by {report.aiUsage.model}.
            </>
          )}
        </footer>
      </main>
    </div>
  );
}
