import Link from "next/link";
import { notFound } from "next/navigation";
import { PageTitle, TopNav } from "@/components/TopNav";
import { CroStepSection } from "@/components/CroStep";
import { CroGenerateButton } from "@/components/CroGenerateButton";
import { CroShareButton } from "@/components/CroShareButton";
import { getCroEdits, getCroReport, getStoreConfig } from "@/lib/data";
import { formatDate } from "@/lib/format";
import { CRO_STEP_KEYS, CRO_STEP_LABELS, type CroStepKey } from "@/lib/shared";

export const dynamic = "force-dynamic";

/** Presentation order, which is not execution order.
 *
 * Key Insights is written last — it is a synthesis of everything else — and shown first, because
 * that is where a deck opens. Encoding that here rather than relying on the order the steps happen
 * to have been written into the report means a regenerated step cannot reorder the deck. */
const PRESENTATION_ORDER: CroStepKey[] = ["insights", "analytics", "ux", "behaviour", "voc", "journey", "competitors"];

export default async function CroReportPage({ params }: { params: Promise<{ slug: string; id: string }> }) {
  const { slug, id } = await params;
  const [report, edits, config] = await Promise.all([getCroReport(slug, id), getCroEdits(slug, id), getStoreConfig(slug)]);
  if (!report) notFound();

  // Presentation order, but only among the steps that have something to present. A step that has not
  // run yet is an empty card, and leaving those in place put two of them above the only section with
  // findings in it — so the reader's first screen was a list of what is missing. What is missing is
  // said once, in the banner below, and the steps themselves are collected underneath the work.
  const ordered = PRESENTATION_ORDER.flatMap((key) => {
    const step = report.steps[key];
    return step ? [step] : [];
  });
  const steps = ordered.filter((step) => step.status === "generated" || step.status === "insufficient");
  const outstanding = ordered.filter((step) => step.status === "pending" || step.status === "skipped");
  const generated = CRO_STEP_KEYS.filter((key) => report.steps[key]?.status === "generated");
  const pending = CRO_STEP_KEYS.filter((key) => report.steps[key]?.status === "pending");

  return (
    <div className="min-h-screen bg-[#f9f8f6]">
      <TopNav />
      <PageTitle title={`CRO Audit — ${report.storeName}`}>
        <Link
          href={`/cro/${slug}/${id}/deck`}
          className="text-sm font-medium text-[#1A1A1A] bg-[#f0efed] hover:bg-[#EDECE8] px-3.5 py-2 rounded-lg transition-colors"
        >
          Deck view
        </Link>
        <CroShareButton slug={slug} croId={id} />
      </PageTitle>

      <main className="max-w-[1040px] mx-auto px-5 lg:px-8 py-8">
        <header className="mb-8">
          <p className="text-sm text-[#6B6B6B]">
            {report.storeUrl} · captured {formatDate(report.createdAt)} ·{" "}
            {generated.length} of {CRO_STEP_KEYS.length} steps generated
            {report.generatedBy ? ` · last generated by ${report.generatedBy}` : ""}
          </p>
          <nav aria-label="Steps" className="mt-4 flex flex-wrap gap-1.5">
            {[...steps, ...outstanding].map((step) => (
              <a
                key={step.key}
                href={`#step-${step.key}`}
                className={`text-[12px] px-2.5 py-1 rounded-md border transition-colors ${
                  step.status === "generated"
                    ? "border-[#E5E5E5] bg-white text-[#1A1A1A] hover:bg-[#f0efed]"
                    : "border-[#E5E5E5] bg-[#fafafa] text-[#9A9A9A]"
                }`}
              >
                {CRO_STEP_LABELS[step.key]}
              </a>
            ))}
          </nav>
        </header>

        {pending.length > 0 && (
          <div className="mb-8 bg-white border border-[#E5E5E5] rounded-lg px-5 py-4">
            <h2 className="text-sm font-semibold text-[#1A1A1A]">
              {pending.length} step{pending.length === 1 ? "" : "s"} still to generate
            </h2>
            <p className="mt-1 text-[13px] text-[#6B6B6B] leading-relaxed max-w-[75ch]">
              {pending.map((key) => CRO_STEP_LABELS[key]).join(" and ")} read the store&rsquo;s GA4 property and the
              steps already written. Neither needs a browser, so both run here rather than from a capture.
            </p>
            <div className="mt-3">
              <CroGenerateButton slug={slug} croId={id} hasGa4={Boolean(config?.ga4PropertyId)} />
            </div>
          </div>
        )}

        <div className="space-y-12">
          {steps.map((step) => (
            <CroStepSection
              key={step.key}
              step={step}
              slug={slug}
              croId={id}
              edits={edits?.bullets ?? {}}
              editable
            />
          ))}
        </div>

        {outstanding.length > 0 && (
          <section className="mt-12 pt-8 border-t border-[#E5E5E5]">
            <h2 className="text-lg font-semibold text-[#000000] tracking-tight">Not in this audit yet</h2>
            <p className="mt-1 text-[13px] text-[#6B6B6B] leading-relaxed max-w-[75ch]">
              Each of these says whether it is waiting on a step that can be run, or on part of the
              process this tool does not do yet. Both matter to whoever presents the deck.
            </p>
            <ul className="mt-4 bg-white border border-[#E5E5E5] rounded-lg divide-y divide-[#E5E5E5]">
              {outstanding.map((step) => (
                <li key={step.key} className="px-5 py-4" id={`step-${step.key}`}>
                  <div className="flex flex-wrap items-baseline justify-between gap-x-4">
                    <h3 className="text-sm font-semibold text-[#1A1A1A]">{CRO_STEP_LABELS[step.key]}</h3>
                    <span
                      className={`text-[11px] font-semibold ${step.status === "pending" ? "text-[#D97706]" : "text-[#9A9A9A]"}`}
                    >
                      {step.status === "pending" ? "Can be generated now" : "Still done by hand"}
                    </span>
                  </div>
                  {step.limitations.map((limitation, i) => (
                    <p key={i} className="mt-1.5 text-[12.5px] text-[#6B6B6B] leading-relaxed max-w-[85ch]">
                      {limitation}
                    </p>
                  ))}
                </li>
              ))}
            </ul>
          </section>
        )}

        {generated.length > 0 && (
          <div className="mt-10 pt-5 border-t border-[#E5E5E5] flex flex-wrap items-center gap-4">
            <CroGenerateButton
              slug={slug}
              croId={id}
              hasGa4={Boolean(config?.ga4PropertyId)}
              label="Regenerate analytics & key insights"
            />
            <p className="text-[11px] text-[#9A9A9A] max-w-[50ch] leading-relaxed">
              Regenerating rewrites those two steps. Hand edits are kept, and any that no longer match a bullet are
              flagged rather than dropped.
            </p>
          </div>
        )}

        <footer className="mt-12 pt-5 border-t border-[#E5E5E5] text-[11.5px] text-[#9A9A9A] leading-relaxed">
          <b className="text-[#6B6B6B]">Methodology.</b> Each page group was loaded once per device in a real browser,
          with the page scrolled to trigger lazy sections before anything was measured. The fold and scroll figures are a
          proxy for where attention stops: they say what a visitor would have to scroll past, not what any visitor
          actually did. Feature comparisons are detected from markup — a tick means the feature was found on the site,
          not that it is implemented well. Analytics figures are GA4&rsquo;s, over 28 complete days ending yesterday, and
          every number on this page was computed by this tool rather than written by a model.
          {report.aiUsage && (
            <>
              {" "}
              <b className="text-[#6B6B6B]">AI usage.</b> The slides were written by {report.aiUsage.model} using{" "}
              {report.aiUsage.inputTokens.toLocaleString()} input and {report.aiUsage.outputTokens.toLocaleString()}{" "}
              output tokens ({report.aiUsage.totalTokens.toLocaleString()} total, ≈$
              {report.aiUsage.estimatedCostUsd.toFixed(4)}).
            </>
          )}
        </footer>
      </main>
    </div>
  );
}
